#!/usr/bin/env python3
"""Generate figures and summary macros for the DroneRace progress slide deck.

This script pulls the W&B run history for the evidence run, combines it with the
current DroneRace task YAML and local git metadata, and produces a reproducible
set of charts for the Beamer presentation in docs/drone_race_progress_slides.tex.
"""

from __future__ import annotations

import argparse
import math
import subprocess
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import wandb
import yaml
from matplotlib import patches


BERKELEY_BLUE = "#003262"
BERKELEY_LIGHT_BLUE = "#3B7EA1"
CALIFORNIA_GOLD = "#FDB515"
BUG_RED = "#B7262E"
SOFT_RED = "#D96666"
SLATE = "#5B6F82"
FOG = "#E8EEF4"
CHARCOAL = "#1B2733"
GREEN = "#2A7F62"


def run_cmd(cmd: list[str]) -> str:
    return subprocess.check_output(cmd, text=True).strip()


def millions(values: pd.Series | np.ndarray) -> np.ndarray:
    return np.asarray(values, dtype=float) / 1_000_000.0


def format_float(value: float, digits: int = 2) -> str:
    return f"{value:.{digits}f}"


def get_git_date(commit: str) -> str:
    return run_cmd(["git", "show", "-s", "--format=%ad", "--date=short", commit])


def latest_series(history: pd.DataFrame, metric: str) -> tuple[np.ndarray, np.ndarray]:
    frame = history[["env_frames", metric]].dropna()
    return frame["env_frames"].to_numpy(dtype=float), frame[metric].to_numpy(dtype=float)


def load_track(task_yaml: Path) -> dict:
    with task_yaml.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def fetch_run(run_path: str):
    api = wandb.Api()
    run = api.run(run_path)
    history = run.history(samples=2000)
    return run, history


def phase_transition_frames(history: pd.DataFrame) -> dict[str, float]:
    phase = history[["env_frames", "curriculum/phase"]].dropna()
    if phase.empty:
        return {"phase1": math.nan, "phase2": math.nan}
    phase1 = phase.loc[phase["curriculum/phase"] >= 0.95, "env_frames"]
    phase2 = phase.loc[phase["curriculum/phase"] >= 1.95, "env_frames"]
    return {
        "phase1": float(phase1.iloc[0]) if not phase1.empty else math.nan,
        "phase2": float(phase2.iloc[0]) if not phase2.empty else math.nan,
    }


def save_numbers_tex(output_path: Path, summary: dict, transitions: dict[str, float]) -> None:
    lap_pct = 100.0 * float(summary["race/lap_completion_rate"])
    crash_pct = 100.0 * float(summary["crash/total_rate"])
    gate11 = float(summary["gates/gate_11_crosses"])
    lines = [
        "% Auto-generated by docs/generate_drone_race_progress_assets.py",
        "\\newcommand{\\EvidenceRunID}{\\texttt{dwn4jigo}}",
        "\\newcommand{\\EvidenceRunURL}{https://wandb.ai/ee106b/omnidrones/runs/dwn4jigo}",
        f"\\newcommand{{\\LapCompletionPct}}{{{lap_pct:.1f}\\%}}",
        f"\\newcommand{{\\GatesPerEpisode}}{{{float(summary['race/gates_passed_per_ep']):.2f}}}",
        f"\\newcommand{{\\LapTimeSeconds}}{{{float(summary['race/lap_time_sec']):.2f}\\,s}}",
        f"\\newcommand{{\\MeanSpeedMs}}{{{float(summary['race/mean_speed_ms']):.2f}\\,m/s}}",
        f"\\newcommand{{\\MaxSpeedMs}}{{{float(summary['race/max_speed_ms']):.2f}\\,m/s}}",
        f"\\newcommand{{\\CrashRatePct}}{{{crash_pct:.1f}\\%}}",
        f"\\newcommand{{\\EntropyCoef}}{{{float(summary['entropy/current_coef']):.5f}}}",
        f"\\newcommand{{\\CurriculumPhase}}{{{int(round(float(summary['curriculum/phase'])) )}}}",
        f"\\newcommand{{\\AccuracyEMA}}{{{float(summary['curriculum/accuracy_ema']):.3f}}}",
        f"\\newcommand{{\\GateElevenCrosses}}{{{gate11:.3f}}}",
        f"\\newcommand{{\\PhaseOneFramesM}}{{{transitions['phase1'] / 1_000_000.0:.1f}M}}",
        f"\\newcommand{{\\PhaseTwoFramesM}}{{{transitions['phase2'] / 1_000_000.0:.1f}M}}",
    ]
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def style_axis(ax, title: str, ylabel: str, xlabel: str = "Environment Frames (Millions)") -> None:
    ax.set_title(title, loc="left", fontsize=12, fontweight="bold", color=BERKELEY_BLUE)
    ax.set_xlabel(xlabel, fontsize=10)
    ax.set_ylabel(ylabel, fontsize=10)
    ax.grid(True, alpha=0.22, linewidth=0.8)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def plot_track_schematic(task_cfg: dict, output_path: Path) -> None:
    track_cfg = task_cfg["track_config"]
    gate_ids = sorted(track_cfg.keys(), key=lambda x: int(x))
    xs = [track_cfg[g]["pos"][0] for g in gate_ids]
    ys = [track_cfg[g]["pos"][1] for g in gate_ids]
    zs = [track_cfg[g]["pos"][2] for g in gate_ids]

    fig = plt.figure(figsize=(11.5, 6.5), constrained_layout=True)
    gs = fig.add_gridspec(1, 2, width_ratios=[1.9, 1.1])
    ax = fig.add_subplot(gs[0, 0])
    ax_side = fig.add_subplot(gs[0, 1])

    for i in range(len(gate_ids) - 1):
        ax.annotate(
            "",
            xy=(xs[i + 1], ys[i + 1]),
            xytext=(xs[i], ys[i]),
            arrowprops=dict(arrowstyle="->", lw=2.0, color=BERKELEY_LIGHT_BLUE, alpha=0.9),
        )

    elevated_ids = {7, 11}
    stack_partner_ids = {8, 12}
    for gid, x, y, z in zip(gate_ids, xs, ys, zs):
        color = BERKELEY_BLUE
        edge = "white"
        size = 220
        if int(gid) in elevated_ids:
            color = CALIFORNIA_GOLD
            edge = BERKELEY_BLUE
            size = 340
        elif int(gid) in stack_partner_ids:
            color = BERKELEY_LIGHT_BLUE
            edge = BERKELEY_BLUE
            size = 280
        if int(gid) == 13:
            color = BUG_RED
            size = 260
        ax.scatter(x, y, s=size, c=color, edgecolors=edge, linewidths=1.8, zorder=3)
        ax.text(x + 0.35, y + 0.35, f"G{gid}", fontsize=10, weight="bold", color=CHARCOAL)

    ax.plot([track_cfg["7"]["pos"][0], track_cfg["8"]["pos"][0]], [track_cfg["7"]["pos"][1], track_cfg["8"]["pos"][1]],
            linestyle="--", color=BUG_RED, linewidth=2, alpha=0.8)
    ax.plot([track_cfg["11"]["pos"][0], track_cfg["12"]["pos"][0]], [track_cfg["11"]["pos"][1], track_cfg["12"]["pos"][1]],
            linestyle="--", color=BUG_RED, linewidth=2, alpha=0.8)

    ax.set_facecolor("#FBFCFE")
    ax.set_title("Top-Down Race Layout from cfg/task/DroneRace.yaml", loc="left",
                 fontsize=13, fontweight="bold", color=BERKELEY_BLUE)
    ax.set_xlabel("X (m)")
    ax.set_ylabel("Y (m)")
    ax.grid(True, alpha=0.22)
    ax.set_aspect("equal", adjustable="box")

    ax_side.axis("off")
    ax_side.set_title("Key Geometry", loc="left", fontsize=13, fontweight="bold", color=BERKELEY_BLUE)
    bullet = (
        "• 13 YAML gate entries, with Gate 13 duplicating Gate 1 for lap closure\n"
        "• Elevated gates: G7 and G11 at z = 3.0 m\n"
        "• Stacked reversals: G7→G8 and G11→G12 share XY but flip height / facing\n"
        "• Hardest maneuvers are the elevated drop-back transitions and lap closure bookkeeping"
    )
    ax_side.text(0.0, 0.82, bullet, fontsize=11, va="top", color=CHARCOAL, linespacing=1.45)

    side_y = np.arange(len(gate_ids))
    ax_side_in = ax_side.inset_axes([0.05, 0.05, 0.9, 0.45])
    colors = [CALIFORNIA_GOLD if int(g) in elevated_ids else BERKELEY_LIGHT_BLUE for g in gate_ids]
    ax_side_in.barh(side_y, zs, color=colors, edgecolor=BERKELEY_BLUE, alpha=0.95)
    ax_side_in.set_yticks(side_y, [f"G{g}" for g in gate_ids], fontsize=8)
    ax_side_in.set_xlabel("Gate origin z (m)", fontsize=9)
    ax_side_in.set_title("Elevation profile", fontsize=10, color=BERKELEY_BLUE, loc="left")
    ax_side_in.grid(True, axis="x", alpha=0.18)
    ax_side_in.spines["top"].set_visible(False)
    ax_side_in.spines["right"].set_visible(False)

    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_pipeline(output_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(12, 4.8))
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 4)
    ax.axis("off")

    boxes = [
        (0.35, 1.3, 2.1, 1.35, BERKELEY_BLUE, "Task YAML\ncfg/task/DroneRace.yaml", "track layout\nreward scales\ncurriculum"),
        (3.0, 1.3, 2.3, 1.35, BERKELEY_LIGHT_BLUE, "DroneRaceEnv", "gate crossings\nstacked reversal logic\nstats + resets"),
        (5.9, 1.3, 2.45, 1.35, CALIFORNIA_GOLD, "PPO Trainer", "2048 envs\n256-step rollouts\n524,288 frames / update"),
        (8.95, 1.3, 2.3, 1.35, GREEN, "W&B Diagnostics", "per-gate stats\nreward breakdown\nresults tracking"),
    ]
    for x, y, w, h, color, title, subtitle in boxes:
        rect = patches.FancyBboxPatch(
            (x, y), w, h,
            boxstyle="round,pad=0.03,rounding_size=0.08",
            facecolor=color, edgecolor=CHARCOAL, linewidth=1.6, alpha=0.95,
        )
        ax.add_patch(rect)
        title_color = "white" if color != CALIFORNIA_GOLD else BERKELEY_BLUE
        subtitle_color = "white" if color not in (CALIFORNIA_GOLD,) else CHARCOAL
        ax.text(x + 0.12, y + 0.92, title, fontsize=12, weight="bold", color=title_color, va="top")
        ax.text(x + 0.12, y + 0.18, subtitle, fontsize=10, color=subtitle_color, va="bottom")

    arrow_y = 1.98
    for x1, x2 in [(2.47, 3.0), (5.32, 5.9), (8.37, 8.95)]:
        ax.annotate("", xy=(x2, arrow_y), xytext=(x1, arrow_y),
                    arrowprops=dict(arrowstyle="->", lw=2.3, color=SLATE))

    aux = patches.FancyBboxPatch(
        (5.35, 3.0), 2.55, 0.62,
        boxstyle="round,pad=0.03,rounding_size=0.08",
        facecolor=FOG, edgecolor=BERKELEY_BLUE, linewidth=1.2,
    )
    ax.add_patch(aux)
    ax.text(5.5, 3.33, "Adaptive entropy + phase curriculum", fontsize=11, weight="bold", color=BERKELEY_BLUE, va="center")
    ax.annotate("", xy=(6.8, 3.0), xytext=(6.8, 2.65), arrowprops=dict(arrowstyle="->", lw=1.8, color=SLATE))

    ax.set_title("Training system grounded in the current codebase", loc="left",
                 fontsize=14, fontweight="bold", color=BERKELEY_BLUE)
    ax.text(0.36, 0.42,
            "Hydra config chooses the task and PPO overrides; the environment exports\n"
            "curriculum statistics that the trainer folds back into exploration control and W&B plots.",
            fontsize=11, color=CHARCOAL)

    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_entropy_curriculum(history: pd.DataFrame, transitions: dict[str, float], output_path: Path) -> None:
    fig, axes = plt.subplots(2, 1, figsize=(11.8, 7.6), sharex=True, constrained_layout=True)
    top = axes[0]
    bottom = axes[1]

    x, entropy = latest_series(history, "entropy/current_coef")
    top.plot(millions(x), entropy, color=BUG_RED, linewidth=2.2, label="entropy/current_coef")
    if "entropy/target_coef" in history.columns:
        xt, target = latest_series(history, "entropy/target_coef")
        top.plot(millions(xt), target, color=SOFT_RED, linewidth=1.5, linestyle="--", label="entropy/target_coef")
    style_axis(top, "Adaptive entropy schedule from dwn4jigo", "Entropy coefficient")
    top.legend(frameon=False, loc="upper right")

    if "curriculum/phase" in history.columns:
        xp, phase = latest_series(history, "curriculum/phase")
        bottom.step(millions(xp), phase, where="post", color=BERKELEY_BLUE, linewidth=2.0, label="curriculum/phase")
    if "curriculum/accuracy_ema" in history.columns:
        xa, acc = latest_series(history, "curriculum/accuracy_ema")
        bottom.plot(millions(xa), acc, color=CALIFORNIA_GOLD, linewidth=2.0, label="curriculum/accuracy_ema")
    if "race/lap_completion_rate" in history.columns:
        xl, lap = latest_series(history, "race/lap_completion_rate")
        bottom.plot(millions(xl), lap, color=GREEN, linewidth=1.8, label="race/lap_completion_rate")
    style_axis(bottom, "Curriculum state and accuracy signal", "Phase / rate")
    bottom.set_ylim(-0.05, 2.2)
    bottom.legend(frameon=False, ncol=3, loc="upper left")

    for ax in axes:
        for key, color in [("phase1", BERKELEY_LIGHT_BLUE), ("phase2", BERKELEY_BLUE)]:
            value = transitions.get(key)
            if value and not math.isnan(value):
                ax.axvline(value / 1_000_000.0, color=color, linestyle=":", linewidth=1.5, alpha=0.9)

    top.text(0.99, 0.03, "Phase 1 unlock and phase 2 speed-focus marked with dotted lines",
             transform=top.transAxes, ha="right", va="bottom", fontsize=9, color=SLATE)
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_results_trends(history: pd.DataFrame, output_path: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(12, 8), constrained_layout=True)
    metrics = [
        ("race/lap_completion_rate", "Lap completion rate", BERKELEY_BLUE),
        ("race/gates_passed_per_ep", "Gates passed / episode", CALIFORNIA_GOLD),
        ("race/mean_speed_ms", "Mean speed (m/s)", GREEN),
        ("reward/total_return", "Episode return", BUG_RED),
    ]
    for ax, (metric, title, color) in zip(axes.flat, metrics):
        x, y = latest_series(history, metric)
        ax.plot(millions(x), y, color=color, linewidth=2.2)
        style_axis(ax, title, title if "return" not in title.lower() else "Return")
    axes[0, 0].set_ylim(0.0, 0.85)
    fig.suptitle("Training trends from the evidence run", x=0.03, y=1.01,
                 ha="left", fontsize=15, fontweight="bold", color=BERKELEY_BLUE)
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_speed_crash(history: pd.DataFrame, output_path: Path) -> None:
    fig, axes = plt.subplots(2, 1, figsize=(11.8, 7.2), sharex=True, constrained_layout=True)
    speed_ax, crash_ax = axes
    for metric, color, label in [
        ("race/mean_speed_ms", GREEN, "mean speed"),
        ("race/max_speed_ms", CALIFORNIA_GOLD, "max speed"),
    ]:
        x, y = latest_series(history, metric)
        speed_ax.plot(millions(x), y, color=color, linewidth=2.0, label=label)
    style_axis(speed_ax, "Speed evolution", "m/s")
    speed_ax.legend(frameon=False, loc="upper left")

    for metric, color, label in [
        ("crash/total_rate", BUG_RED, "total crash"),
        ("crash/contact_rate", BERKELEY_BLUE, "contact"),
        ("crash/ground_rate", SLATE, "ground"),
        ("crash/distance_rate", SOFT_RED, "distance"),
    ]:
        x, y = latest_series(history, metric)
        crash_ax.plot(millions(x), y, color=color, linewidth=2.0, label=label)
    style_axis(crash_ax, "Crash diagnostics", "Rate")
    crash_ax.legend(frameon=False, ncol=4, loc="upper right")
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_reward_components(history: pd.DataFrame, output_path: Path) -> None:
    fig, axes = plt.subplots(2, 1, figsize=(11.8, 7.4), sharex=True, constrained_layout=True)
    top, bottom = axes
    component_specs = [
        ("reward/gates_cumul", BERKELEY_BLUE, "gates"),
        ("reward/speed_cumul", GREEN, "speed"),
        ("reward/stacked_bonus_cumul", CALIFORNIA_GOLD, "stacked bonus"),
        ("reward/penalties_cumul", BUG_RED, "penalties"),
    ]
    for metric, color, label in component_specs:
        if metric in history.columns:
            x, y = latest_series(history, metric)
            if label == "penalties":
                y = np.abs(y)
            top.plot(millions(x), y, color=color, linewidth=2.0, label=label)
    if "reward/total_return" in history.columns:
        x, total = latest_series(history, "reward/total_return")
        top.plot(millions(x), total, color=CHARCOAL, linewidth=2.2, linestyle="--", label="total return")
    style_axis(top, "Reward component magnitudes", "Cumulative reward")
    top.legend(frameon=False, ncol=5, loc="upper left")

    frac_specs = [
        ("reward/gates_fraction", BERKELEY_BLUE, "gates fraction"),
        ("reward/speed_fraction", GREEN, "speed fraction"),
        ("reward/stacked_fraction", CALIFORNIA_GOLD, "stacked fraction"),
    ]
    for metric, color, label in frac_specs:
        if metric in history.columns:
            x, y = latest_series(history, metric)
            bottom.plot(millions(x), y, color=color, linewidth=2.0, label=label)
    style_axis(bottom, "Reward balance over time", "Fraction of return")
    bottom.legend(frameon=False, ncol=3, loc="upper left")
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_gate_crossings(summary: dict, output_path: Path) -> None:
    gates = list(range(12))
    values = [float(summary[f"gates/gate_{i:02d}_crosses"]) for i in gates]
    colors = [BERKELEY_LIGHT_BLUE] * 12
    for idx in [6, 10]:
        colors[idx] = CALIFORNIA_GOLD
    colors[11] = BUG_RED

    fig, ax = plt.subplots(figsize=(11.2, 5.4), constrained_layout=True)
    bars = ax.bar(gates, values, color=colors, edgecolor=BERKELEY_BLUE, linewidth=1.1)
    ax.axhline(1.0, color=SLATE, linestyle="--", linewidth=1.3, alpha=0.85)
    ax.text(11.1, 1.02, "1.0 per-episode expectation threshold", fontsize=9, color=SLATE, va="bottom")
    bars[11].set_edgecolor(BUG_RED)
    bars[11].set_linewidth(2.2)
    ax.annotate(
        f"gate_11_crosses = {values[11]:.3f}\npre-fix anomaly",
        xy=(11, values[11]), xytext=(9.2, values[11] + 0.18),
        arrowprops=dict(arrowstyle="->", color=BUG_RED, lw=1.8),
        fontsize=10, color=BUG_RED,
    )
    ax.set_xticks(gates, [f"G{i}" for i in gates])
    ax.set_ylim(0, max(values) + 0.45)
    style_axis(ax, "Latest per-gate crossing distribution", "Mean crosses / episode", xlabel="Zero-based gate index")
    ax.text(0.01, 0.98,
            "Gold bars = elevated/stacked regions. Gate 11 exceeds 1.0 because dwn4jigo predates the lap-closure accounting fix.",
            transform=ax.transAxes, ha="left", va="top", fontsize=9.5, color=CHARCOAL)
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_reset_curriculum(summary: dict, output_path: Path) -> None:
    fig = plt.figure(figsize=(12, 6.2), constrained_layout=True)
    gs = fig.add_gridspec(1, 2, width_ratios=[1.0, 1.5])
    ax_pie = fig.add_subplot(gs[0, 0])
    ax_bar = fig.add_subplot(gs[0, 1])

    shares = [
        float(summary["curriculum/reset_from_gate0_rate"]),
        float(summary["curriculum/reset_from_prev_gate_rate"]),
        float(summary["curriculum/reset_from_random_rate"]),
    ]
    labels = ["Gate 0", "Previous gate", "Random gate"]
    pie_colors = [BERKELEY_BLUE, BERKELEY_LIGHT_BLUE, CALIFORNIA_GOLD]
    wedges, _texts, _autotexts = ax_pie.pie(
        shares,
        labels=labels,
        autopct=lambda p: f"{p:.0f}%",
        startangle=110,
        colors=pie_colors,
        wedgeprops=dict(width=0.52, edgecolor="white"),
        textprops=dict(color=CHARCOAL, fontsize=10),
    )
    ax_pie.set_title("Reset curriculum mix", loc="left", fontsize=13, fontweight="bold", color=BERKELEY_BLUE)

    gate_ids = np.arange(12)
    emas = [float(summary[f"curriculum/reset_gate_{i:02d}_pass_ema"]) for i in gate_ids]
    active_gate = int(round(float(summary["curriculum/reset_active_gate"])))
    colors = [BERKELEY_LIGHT_BLUE if i != active_gate else BUG_RED for i in gate_ids]
    ax_bar.bar(gate_ids, emas, color=colors, edgecolor=BERKELEY_BLUE, linewidth=1.0)
    ax_bar.axhline(0.90, color=SLATE, linestyle="--", linewidth=1.3, alpha=0.85)
    ax_bar.text(11.1, 0.905, "practice threshold", fontsize=9, color=SLATE, va="bottom", ha="right")
    ax_bar.set_xticks(gate_ids, [f"G{i}" for i in gate_ids])
    ax_bar.set_ylim(0.78, 1.02)
    style_axis(ax_bar, "Per-gate reset-pass EMA", "EMA", xlabel="Zero-based gate index")
    ax_bar.text(0.01, 0.98,
                f"Active gate target ≈ G{active_gate}. Later gates stay below the 0.90 threshold and keep receiving practice resets.",
                transform=ax_bar.transAxes, ha="left", va="top", fontsize=9.5, color=CHARCOAL)
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def draw_mlp(ax, x0: float, y0: float, widths: list[str], color: str, title: str) -> None:
    ax.text(x0, y0 + 1.55, title, fontsize=12, fontweight="bold", color=BERKELEY_BLUE, ha="center")
    for i, label in enumerate(widths):
        rect = patches.FancyBboxPatch(
            (x0 - 0.35, y0 - i * 0.42), 0.7, 0.28,
            boxstyle="round,pad=0.02,rounding_size=0.03",
            facecolor=color if i > 0 else FOG,
            edgecolor=BERKELEY_BLUE,
            linewidth=1.2,
        )
        ax.add_patch(rect)
        ax.text(x0, y0 - i * 0.42 + 0.14, label, ha="center", va="center",
                fontsize=9.5, color=CHARCOAL if i == 0 else ("white" if color != CALIFORNIA_GOLD else BERKELEY_BLUE),
                fontweight="bold")
        if i < len(widths) - 1:
            ax.annotate("", xy=(x0, y0 - i * 0.42 - 0.06), xytext=(x0, y0 - i * 0.42 - 0.13),
                        arrowprops=dict(arrowstyle="->", color=SLATE, lw=1.2))


def plot_network_architecture(output_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(11.8, 6.4))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 4)
    ax.axis("off")

    ax.text(0.1, 3.72, "Architecture expansion from the older report snapshot to dwn4jigo",
            fontsize=14, fontweight="bold", color=BERKELEY_BLUE, ha="left")
    ax.text(0.1, 3.38,
            "Old snapshot widths came from the existing written report. Current widths are pulled from the dwn4jigo run config.",
            fontsize=10.5, color=CHARCOAL, ha="left")

    draw_mlp(ax, 2.2, 2.5, ["Obs + intrinsics", "256", "256", "Action 4"], BERKELEY_LIGHT_BLUE, "Old actor")
    draw_mlp(ax, 4.2, 2.5, ["Obs + intrinsics", "256", "256", "128", "Value"], CALIFORNIA_GOLD, "Old critic")
    draw_mlp(ax, 6.6, 2.5, ["Obs + intrinsics", "512", "512", "Action 4"], BERKELEY_BLUE, "Current actor")
    draw_mlp(ax, 8.7, 2.5, ["Obs + intrinsics", "512", "512", "512", "Value"], GREEN, "Current critic")

    ax.text(0.25, 0.62,
            "Why the wider model helped:\n"
            "• More capacity for long-horizon sequence credit assignment\n"
            "• Better critic fit for sparse ordered-lap rewards\n"
            "• Enough width to preserve accuracy after speed shaping unlocks",
            fontsize=11, color=CHARCOAL, va="top")
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_bug_timeline(output_path: Path) -> None:
    events = [
        ("9985c0f", "Gate-center\nconsistency fix", BERKELEY_LIGHT_BLUE),
        ("316fead", "Curriculum +\nreward shaping", BERKELEY_BLUE),
        ("ece7d19", "Adaptive\nentropy", CALIFORNIA_GOLD),
        ("1133905", "Auto-stop +\nW&B metrics", GREEN),
        ("dwn4jigo", "Evidence run\npre-fix", BUG_RED),
        ("4b808b8", "Gate 11 lap-closure\naccounting fix", CHARCOAL),
    ]

    fig, ax = plt.subplots(figsize=(12, 4.6))
    ax.set_xlim(-0.5, len(events) - 0.5)
    ax.set_ylim(-1.2, 1.2)
    ax.axis("off")
    ax.plot([0, len(events) - 1], [0, 0], color=SLATE, linewidth=2.0)

    for i, (tag, label, color) in enumerate(events):
        y = 0.42 if i % 2 == 0 else -0.42
        ax.scatter(i, 0, s=180, color=color, edgecolor="white", linewidth=1.8, zorder=3)
        ax.plot([i, i], [0, y - 0.08 if y > 0 else y + 0.08], color=color, linewidth=1.6)
        ax.text(i, y, f"{tag}\n{label}", ha="center", va="center", fontsize=10,
                color=CHARCOAL, fontweight="bold")

    ax.text(4, -0.93, "Observed anomaly: gate_11_crosses = 1.505\nThis run is the main evidence source, but it predates the bug fix.",
            ha="center", va="center", fontsize=10.5, color=BUG_RED,
            bbox=dict(boxstyle="round,pad=0.35", fc="#FFF3F3", ec=BUG_RED, lw=1.4))
    ax.set_title("Bug timeline and interpretation guardrail", loc="left",
                 fontsize=14, fontweight="bold", color=BERKELEY_BLUE)
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def generate_assets(run_path: str, task_yaml: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    run, history = fetch_run(run_path)
    task_cfg = load_track(task_yaml)
    summary = dict(run.summary)
    transitions = phase_transition_frames(history)

    plot_track_schematic(task_cfg, output_dir / "drone_race_progress_track_schematic.png")
    plot_pipeline(output_dir / "drone_race_progress_pipeline.png")
    plot_entropy_curriculum(history, transitions, output_dir / "drone_race_progress_entropy_curriculum.png")
    plot_results_trends(history, output_dir / "drone_race_progress_results_trends.png")
    plot_speed_crash(history, output_dir / "drone_race_progress_speed_crash.png")
    plot_reward_components(history, output_dir / "drone_race_progress_reward_components.png")
    plot_gate_crossings(summary, output_dir / "drone_race_progress_gate_crossings.png")
    plot_reset_curriculum(summary, output_dir / "drone_race_progress_reset_curriculum.png")
    plot_network_architecture(output_dir / "drone_race_progress_network_architecture.png")
    plot_bug_timeline(output_dir / "drone_race_progress_bug_timeline.png")
    save_numbers_tex(output_dir / "drone_race_progress_numbers.tex", summary, transitions)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-path", default="ee106b/omnidrones/dwn4jigo")
    parser.add_argument("--task-yaml", default="cfg/task/DroneRace.yaml")
    parser.add_argument("--output-dir", default="docs/figures")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    generate_assets(args.run_path, Path(args.task_yaml), Path(args.output_dir))


if __name__ == "__main__":
    main()
